version: 2
updates:
  # Java/Maven dependencies
  - package-ecosystem: "maven"
    directory: "/java-audio-bridge"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "LydByDissing"
    assignees:
      - "LydByDissing"
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "java"
    # Group minor and patch updates
    groups:
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
      
  # Docker base images
  - package-ecosystem: "docker"
    directory: "/pi-receiver"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "LydByDissing"
    commit-message:
      prefix: "docker"
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
      
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
    open-pull-requests-limit: 3
    reviewers:
      - "LydByDissing"
    commit-message:
      prefix: "ci"
      include: "scope"
    labels:
      - "dependencies"
      - "github-actions"