name: Dependabot Auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot-auto-merge:
    name: Auto-merge Dependabot PRs
    runs-on: ubuntu-latest
    if: github.actor == 'dependabot[bot]'
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Check if PR is from Dependabot
      id: dependabot-check
      run: |
        if [[ "${{ github.actor }}" == "dependabot[bot]" ]]; then
          echo "is_dependabot=true" >> $GITHUB_OUTPUT
        else
          echo "is_dependabot=false" >> $GITHUB_OUTPUT
        fi
        
    - name: Wait for CI to complete
      if: steps.dependabot-check.outputs.is_dependabot == 'true'
      uses: fountainhead/action-wait-for-check@v1.2.0
      id: wait-for-ci
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        checkName: 'CI Pipeline'
        timeoutSeconds: 1800  # 30 minutes
        intervalSeconds: 30
        
    - name: Auto-approve Dependabot PR
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.wait-for-ci.outputs.conclusion == 'success'
      run: |
        gh pr review --approve "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Auto-merge Dependabot PR
      if: steps.dependabot-check.outputs.is_dependabot == 'true' && steps.wait-for-ci.outputs.conclusion == 'success'
      run: |
        gh pr merge --auto --squash "${{ github.event.pull_request.number }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}